version: '1'
services:
    db:
        image: mysql:8.0.34
        ports:
            - "33061:3306"
        command: --init-file /data/app/init.sql
        volumes:
            - ./init.sql:/data/app/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: local 
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            retries: 10
    webapp:
        build: .
        command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy