version: '3.8'
services:
    db:
        build:
            context: .
            dockerfile: Dockerfile.db 
        ports:
            - "33061:3306"
        command: --init-file /etc/mysql/conf.d/init.sql
        volumes:
            - ./init.sql:/etc/mysql/conf.d/init.sql
            - ./my.cnf:/etc/mysq/conf.d/my.cnf
    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"