"""
data_endpoint apps generated by running python manage.py startapp data_endpoints
"""

from django.apps import AppConfig

class DataEndpointsConfig(AppConfig):
    '''DataEndpointsConfig class'''
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'data_endpoints'
