"""
Django apps for login project.

Generated by 'django-admin startApp login' using Django 4.2.4.
"""

from django.apps import AppConfig

class LoginConfig(AppConfig):
    '''Class for login config'''
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'login'
