"""
Django views for student_view project.

Generated by 'django-admin startApp student_view' using Django 4.2.4.
"""

from django.shortcuts import render
from django.http import JsonResponse
import json

req1 = {
    'id': 1,
    'course': 'COMP30022',
    'dateCreated': '28/11/2001',
    'status': 'pending',
    'message': 'The dog ate my homework',

}
req2 = {
    'id': 2,
    'course': 'COMP30026',
    'dateCreated': '1/1/2023',
    'status': 'approved',
    'message': 'The cat ate my homework',
    
}

def home_view(request):
    return render(request, 'sHome.html', {})

def submit_req_view(request):
    return render(request, 'submitRequest.html', {})

def cases_view(request):
    return render(request, 'viewCases.html', {})

def aaps_view(request):
    return render(request, 'viewAAPs.html', {})

def view_req_view(request, id):
    # check the id exists

    if(id == req1['id']):
        req = json.dumps(req1)
        return render(request, 'viewRequest.html', {'req':req})
    elif(id == req2['id']):
        req = json.dumps(req2)
        return render(request, 'viewRequest.html', {'req':req})
    else:
        return JsonResponse({'error': 'Record not found'}, status=404)