"""
Django apps for instructor_view project.

Generated by 'django-admin startApp instructor_view' using Django 4.2.4.
"""

from django.apps import AppConfig

class InstructorviewConfig(AppConfig):
    """Class generated by above command"""
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'instructor_view'
