"""
Django test for instructor_view project.

Generated by 'django-admin startApp instructor_view' using Django 4.2.4.
"""

# fake data to play with before DB connected
usr3 = {
    'user_id': 3,
    'name' : 'Ryan Goh',
    'first_name': 'Ryan',
    'last_name': 'Goh',
    'email': 'insertEmailHereLol@student.unimelb.edu.au',
    'email_preference': 1,
    'darkmode_preference': 1,
}
usr4 = {
    'user_id': 4,
    'name' : 'Yan Zong Goh',
    'first_name': 'Yan Zong',
    'last_name': 'Goh',
    'email': 'thisIsAnEmail@student.unimelb.edu.au',
    'email_preference': 1,
    'darkmode_preference': 1,
}
# fake user 3s courses
course31 = {
    'course_id': '31',
    'course_name': 'IT Project',
    'course_code': 'COMP30022',
}
course32 = {
    'course_id': '32',
    'course_name': 'Computer Systems',
    'course_code': 'COMP30023',
}
#fake user 4s courses
course41 = {
    'course_id': '41',
    'course_name': 'Graphics and Interaction',
    'course_code': 'COMP30019',
}
course42 = {
    'course_id': '42',
    'course_name': 'Models of Computation',
    'course_code': 'COMP30026',
}
# fake course 31 and 41 requests
req311 = {
    'request_id': 311,
    'thread_id': 456,
    'date_created': "11-09-2023",
    'request_content': 'The dog ate my homework. L',
    'instructor_notes': 'This was a bad excuse lol',
}
req312 = {
    'request_id': 312,
    'thread_id': 457,
    'date_created': "17-12-2023",
    'request_content': 'The cat ate my homework. L',
    'instructor_notes': ';lksadf;lksdaf;lksdfa;lkdsfa;lkdsfa;lksdaf',
}
# fake course 32 and 42 requests
req321 = {
    'request_id': 321,
    'thread_id': 458,
    'date_created': "01-19-2023",
    'request_content': 'Im very sick *sad face*',
    'instructor_notes': 'bingbongbingbong',
}
req322 = {
    'request_id': 322,
    'thread_id': 459,
    'date_created': "01-19-2023",
    'request_content': 'Please just give me an extension, im begging',
    'instructor_notes': 'AHHHHHHHHHHHHH',
}

subjSettings = {
    'globalExtentionLength': 1,
    'generalTutor': 1,
    'extensionTutor': 1,
    'quizTutor': 1,
    'remarkTutor': 1,
    'otherTutor': 1,    
    'generalScoord': 1,
    'extensionScoord': 1,
    'quizScoord': 1,
    'remarkScoord': 1,
    'otherScoord': 1,
    'generalReject': 'Message',
    'extensionApprove': 'Message',
    'extensionReject': 'Message',
    'quizApprove': 'Message',
    'quizReject': 'Message',
    'remarkApprove': 'Message',
    'remarkReject': 'Message',
}
