"""
Django views for instructor_view project.

Generated by 'django-admin startApp instructor_view' using Django 4.2.4.
"""

import json
from django.shortcuts import render

def not_found_view(request):
    '''View not found'''
    return render(request, 'notFound404.html', {})

def home_view(request):
    '''Home view'''
    return render(request, 'iHome.html', {})

def instructor_web_header_view(request):
    ''' take the id and edit header with initial data '''
    return render(request, 'iWebHeader.html', {})

def review_req_view(request, thread_id):
    ''' check the id exists '''
    return render(request, 'reviewRequest.html', {'thread_id': thread_id})

def view_reqs_view(request, input_id):
    ''' View requests view '''
    return render(request, 'viewRequests.html',
                  {'course': json.dumps({
                        'course_id': '31',
                        'course_name': 'IT Project',
                        'course_code': 'COMP30022',
                    })})

def view_resolved_view(request, thread_id):
    '''View resolved requests'''
    print(thread_id) # To make pylint happy
    return render(request, 'viewResolved.html', {'thread_id': thread_id})

def subj_settings_view(request, input_id):
    '''View for subject preferences'''
    # Check the ID exists
    req = json.dumps({
        'course_id': '31',
        'course_name': 'IT Project',
        'course_code': 'COMP30022',
    })
    return render(request, 'subjectSettings.html', {'req':req})

def view_profile_view(request, user_id):
    '''View for student profile'''
    return render(request, 'viewProfile.html', {'user_id':user_id})
